Create animals table
peter-akhigbe/vet_clinic pull request #1
Opened 2023-06-05 17:57 UTC by peter-akhigbe

This pull request includes the completion of the Vet Clinic Database project. The project involved creating a database structure to store information about animals in a vet clinic, inserting data into the table, and writing SQL queries to retrieve specific information.

Changes Made:

- Created the vet_clinic database.
- Added the animals' table with the required columns (id, name, date_of_birth, escape_attempts, neutered, weight_kg).
- Populated the animals' table with sample data.
- Wrote SQL queries to fulfil the given quests.
- Captured screenshots of the query results.

Screenshot: 
<img width="682" alt="Screenshot 2023-06-05 at 6 38 46 PM" src="https://github.com/peter-akhigbe/vet_clinic/assets/12002619/2dc7344f-19dd-43dd-b23b-d43a2a6bd4df">

2023-06-05 19:05 UTC, bobb-Rob requested changes
## STATUS: CHANGES REQUIRED ♻️
Hi @peter-akhigbe, 

Good job so far! 👏👏👏 
There are some issues that you still need to work on to go to the next project but you are almost there!  😃 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>
![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of Gitflow
✅ Very descriptive Pull Request(PR)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-05 19:05 UTC, bobb-Rob commented on queries.sql
> +
- [ ] The provided query solution uses multiple conditions connected by the OR operator (OR) in a single query. When executed, this query will return a combined result set that satisfies ANY of the conditions.

You are expected to address each query question individually and obtain separate responses, hence, you would need to execute each query separately, focusing on one condition at a time. Here's an example breakdown of how you can execute the queries individually:

```sql
/* Find all animals whose name ends in "mon": */
SELECT *
FROM animals
WHERE name LIKE '%mon';

# List the name of all animals born between 2016 and 2019: 
SELECT name
FROM animals
WHERE date_of_birth BETWEEN '2016-01-01' AND '2019-12-31';

/* As so on .... */
```

Please place each query question above each query as seen in the example above. This will improve readability and ease the reviewer. 

Also, on your Pull Request, add individual screenshots each with a label(query question as a label) above it, like so 👇🏾 
Find all animals whose name ends in "mon":

![image](https://github.com/peter-akhigbe/vet_clinic/assets/84156714/0c585975-1166-4d40-b745-67517b3ba93e)

List the name of all animals born between 2016 and 2019: 

![image](https://github.com/peter-akhigbe/vet_clinic/assets/84156714/58eb610e-678d-46f0-9fc8-8f5d3d10f88f)

2023-06-05 20:12 UTC, peter-akhigbe commented
### 1. Find all animals whose name ends in "mon".
<img width="682" alt="Screenshot 2023-06-05 at 8 50 12 PM" src="https://github.com/peter-akhigbe/vet_clinic/assets/12002619/a766584d-c00d-4278-b2bf-d6a1e3b2e0cb">

### 2. List the name of all animals born between 2016 and 2019.
<img width="850" alt="Screenshot 2023-06-05 at 8 51 45 PM" src="https://github.com/peter-akhigbe/vet_clinic/assets/12002619/c2ae74e7-a248-4fb7-8ad9-01ebffad4103">

### 3. List the name of all animals that are neutered and have less than 3 escape attempts.
<img width="850" alt="Screenshot 2023-06-05 at 8 54 57 PM" src="https://github.com/peter-akhigbe/vet_clinic/assets/12002619/1d44d524-9975-4c9c-9d40-af461e6b573f">

### 4. List the date of birth of all animals named either "Agumon" or "Pikachu".
<img width="850" alt="Screenshot 2023-06-05 at 8 55 50 PM" src="https://github.com/peter-akhigbe/vet_clinic/assets/12002619/dd129c2e-821b-44a3-98f8-fb1be0d021a6">

### 5. List name and escape attempts of animals that weigh more than 10.5kg
<img width="724" alt="Screenshot 2023-06-05 at 8 56 56 PM" src="https://github.com/peter-akhigbe/vet_clinic/assets/12002619/1d9f9fbf-0ab1-4f83-848b-3bcdcf1c70a2">

### 6. Find all animals that are neutered.
<img width="724" alt="Screenshot 2023-06-05 at 8 57 22 PM" src="https://github.com/peter-akhigbe/vet_clinic/assets/12002619/48c24539-debe-4c1f-b074-f87cccaaad21">

### 7. Find all animals not named Gabumon.
<img width="724" alt="Screenshot 2023-06-05 at 8 57 37 PM" src="https://github.com/peter-akhigbe/vet_clinic/assets/12002619/a8c82c02-5aa8-4005-b8b3-91ba7353b74d">

### 8. Find all animals with a weight between 10.4kg and 17.3kg.
<img width="724" alt="Screenshot 2023-06-05 at 8 58 10 PM" src="https://github.com/peter-akhigbe/vet_clinic/assets/12002619/3042f7a8-ce93-4c0e-ac65-4dae78c875c8">

2023-06-05 20:58 UTC, DuaneDave approved these changes
Hi @peter-akhigbe 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Correct query builds

## Optional suggestions
N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-09 21:42 UTC, merged

2023-07-15 09:56 UTC, codecaiine reviewed
Hi @peter-akhigbe , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Good database setup ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._