Query And Update Animals Table
peter-akhigbe/vet_clinic pull request #2
Opened 2023-06-09 22:27 UTC by peter-akhigbe

This pull request implements the necessary modifications and queries for the Animals table in accordance with the project requirements. The following changes have been made:

- Added a new column "species" of type string to the Animals table.
- Inserted new animal data with the specified details.
- Implemented transactions for updating the species column, rolling back changes, and verifying the rollback.
- Updated the species column based on specific conditions.
- Performed transactions to delete and rollback records in the Animals table.
- Executed transactions to delete, update, and rollback based on conditions involving animal birth dates and weights.
- Added SQL queries to answer the provided questions related to animal data.

Please review this pull request. Screenshots of the query results and transaction actions have been included in the pull request description for reference.

2023-06-09 22:32 UTC, peter-akhigbe commented
- Before setting the species column to "unspecified".

<img width="780" alt="Screenshot 2023-06-09 at 11 20 23 PM" src="https://github.com/peter-akhigbe/vet_clinic/assets/12002619/f748a8a4-1115-408b-b54b-7dfa0dd66890">

- After setting the species column to "unspecified".

<img width="780" alt="Screenshot 2023-06-09 at 11 20 28 PM" src="https://github.com/peter-akhigbe/vet_clinic/assets/12002619/119d9987-ac5a-40b1-88e7-e662f4fb6bca">

- ROLLBACK

<img width="780" alt="Screenshot 2023-06-09 at 11 21 03 PM" src="https://github.com/peter-akhigbe/vet_clinic/assets/12002619/ae6d3f87-7f11-4da6-8bdf-4674b6279635">

2023-06-09 22:39 UTC, peter-akhigbe commented
Update the animals table by setting the species column to "digimon" for animals with names ending in "mon", and set it to "pokemon" for animals without a species already set.

- Verify changes persist after commit

<img width="780" alt="Screenshot 2023-06-09 at 11 34 10 PM" src="https://github.com/peter-akhigbe/vet_clinic/assets/12002619/cc07e99c-1748-4751-b6e4-841b5d2f3283">

2023-06-09 22:47 UTC, peter-akhigbe commented
Delete all records in the animals table, and then roll back the transaction.

- Verify deletion

<img width="736" alt="Screenshot 2023-06-09 at 11 41 45 PM" src="https://github.com/peter-akhigbe/vet_clinic/assets/12002619/f1c4685d-9204-4a29-8536-21dc29a69990">

- Verify rollback

<img width="780" alt="Screenshot 2023-06-09 at 11 42 04 PM" src="https://github.com/peter-akhigbe/vet_clinic/assets/12002619/bf5d3349-aee4-4197-8d4c-15e7afdee8d5">

2023-06-09 23:12 UTC, peter-akhigbe commented
- Delete all animals born after Jan 1st, 2022.
- Create a savepoint for the transaction.

<img width="780" alt="Screenshot 2023-06-10 at 12 10 46 AM" src="https://github.com/peter-akhigbe/vet_clinic/assets/12002619/86204ffa-4973-4f7e-8e14-653b227160b3">

- Update all animals' weight to be their weight multiplied by -1.

<img width="780" alt="Screenshot 2023-06-10 at 12 02 36 AM" src="https://github.com/peter-akhigbe/vet_clinic/assets/12002619/565bb86f-864b-49d3-a3ca-abbd5867aba6">

- Rollback to the savepoint
- Update all animals' weights that are negative to be their weight multiplied by -1.
- Commit transaction
- Verify changes

<img width="780" alt="Screenshot 2023-06-10 at 12 02 57 AM" src="https://github.com/peter-akhigbe/vet_clinic/assets/12002619/b355305f-af95-4b86-82ef-9ff3799248cd">

2023-06-09 23:44 UTC, peter-akhigbe commented
# Queries

- How many animals are there?
<img width="780" alt="Screenshot 2023-06-10 at 12 35 30 AM" src="https://github.com/peter-akhigbe/vet_clinic/assets/12002619/b56b67ff-9676-42f6-9a3a-4adcd877a32f">


- How many animals have never tried to escape?
<img width="780" alt="Screenshot 2023-06-10 at 12 37 09 AM" src="https://github.com/peter-akhigbe/vet_clinic/assets/12002619/cc8ac359-3549-4455-bcb6-c108d9bd6a85">


- What is the average weight of animals?
<img width="780" alt="Screenshot 2023-06-10 at 12 37 19 AM" src="https://github.com/peter-akhigbe/vet_clinic/assets/12002619/ff49db70-0e0c-474e-9a32-be89af2f9a75">


- Who escapes the most, neutered or not neutered animals?
<img width="780" alt="Screenshot 2023-06-10 at 12 37 37 AM" src="https://github.com/peter-akhigbe/vet_clinic/assets/12002619/caf13346-fdfa-40b2-8302-f7ce616ac1ad">


- What is the minimum and maximum weight of each type of animal?
<img width="780" alt="Screenshot 2023-06-10 at 12 38 04 AM" src="https://github.com/peter-akhigbe/vet_clinic/assets/12002619/ac19b6f8-95fa-4d60-882f-81251488b6ff">


- What is the average number of escape attempts per animal type of those born between 1990 and 2000?
<img width="780" alt="Screenshot 2023-06-10 at 12 38 22 AM" src="https://github.com/peter-akhigbe/vet_clinic/assets/12002619/fa350e55-5b64-4fc3-8300-46fafba094b9">

2023-06-09 23:56 UTC, alexander16108 approved these changes
Hi @peter-akhigbe  , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

<img src="https://media4.giphy.com/media/wAjfQ9MLUfFjq/giphy.gif"/>

## Highlights
good  pr
proper readme file

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-10 00:01 UTC, alexander16108 requested changes
Hi @peter-akhigbe , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media3.giphy.com/media/dtBi0s3hndz7q/giphy.gif"/>

## Required Changes ♻️
_Check the comments under the review._

- please fix the broken license link found on your readme file because it is highly unprofessional to have broken links on your codebase

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- please add those screenshots to your PR description, not as comments on the PR to make your PR look neat. 👍🏾 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-10 00:29 UTC, KanzaTahreem requested changes
# Changes Required 🔁

Hi @peter-akhigbe 🙋‍♀️

Good job so far! I really appreciate the effort you put in!  **_However, there are few things that still need to be fixed. But you are almost there!_** 💪 🏁

![so_close](https://user-images.githubusercontent.com/99715640/211022680-440a1bb1-4281-4acb-8dbc-3442fe509063.gif)

## Highlights 🎯

There are some excellent points that you have made perfectly. Keep up the great work! 👏
- ✅ Great work using correct Gitflow
- ✅ Descriptive PR title & description


## Required Changes 🛑


_Please check the comments under the review._

## Optional suggestions ❕
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

N/A

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-10 00:29 UTC, KanzaTahreem commented on README.md
>  This project is [MIT](./LICENSE) licensed.
- [ ] As suggested, please make sure that the LICENSE link is not broken for documenting a professional README. Right now, I am getting the _**File not found**_ error⚠ I can not see a LICENSE file in your repo. Can you please look into this? 😃
  ![image](https://github.com/peter-akhigbe/vet_clinic/assets/106119105/233659a3-e89e-4c96-9d1f-005afd379a32)

2023-06-10 00:37 UTC, Zuhaib042 approved these changes
Hi @peter-akhigbe 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![](https://media.giphy.com/media/QJsP0cTAJhg7O47ub2/giphy.gif)
## Highlights
✅ Professional Readme
✅ Implemented suggested changes
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-10 00:39 UTC, merged

2023-07-15 10:23 UTC, Felix45 reviewed
# Approved :green_circle: 
Hi @peter-akhigbe, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://user-images.githubusercontent.com/38088818/253566971-43d45e44-98b5-4608-a589-53a38ffb3ea1.gif" width="350px" />

## Highlights :heavy_check_mark: 
- [x] Good SQL query design :white_check_mark: 
- [x] Git flow is used correctly :white_check_mark:  
- [x] Pull request has a descriptive title and summary :white_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._