Add join table for visits
peter-akhigbe/vet_clinic pull request #4
Opened 2023-06-10 17:19 UTC by peter-akhigbe

This pull request adds support for many-to-many relationships and introduces more complex queries to handle these relationships in the project. The changes include creating join tables for specializations and visits, inserting data for vets, specialties, and visits, and writing queries to answer various questions based on the new data.

2023-06-10 17:24 UTC, peter-akhigbe commented
# Queries

- Who was the last animal seen by William Tatcher?
<img width="647" alt="Screenshot 2023-06-10 at 5 54 17 PM" src="https://github.com/peter-akhigbe/vet_clinic/assets/12002619/55c88bee-63ac-4c97-a4c7-981296fe40aa">

- How many different animals did Stephanie Mendez see?
<img width="647" alt="Screenshot 2023-06-10 at 5 54 35 PM" src="https://github.com/peter-akhigbe/vet_clinic/assets/12002619/2aba1430-873b-43b7-881a-b7634ade15ca">

- List all vets and their specialties, including vets with no specialties.
<img width="745" alt="Screenshot 2023-06-10 at 5 55 03 PM" src="https://github.com/peter-akhigbe/vet_clinic/assets/12002619/a9224d0f-9b68-4534-83a9-f90993082944">

- List all animals that visited Stephanie Mendez between April 1st and August 30th, 2020.
<img width="857" alt="Screenshot 2023-06-10 at 5 55 29 PM" src="https://github.com/peter-akhigbe/vet_clinic/assets/12002619/951ff2d9-2d9b-4cd2-b16e-3342ad7d957d">

- What animal has the most visits to vets?
<img width="563" alt="Screenshot 2023-06-10 at 5 55 56 PM" src="https://github.com/peter-akhigbe/vet_clinic/assets/12002619/4eecd504-26d4-4e5f-964e-764352e626ad">

- Who was Maisy Smith's first visit?
<img width="722" alt="Screenshot 2023-06-10 at 6 07 15 PM" src="https://github.com/peter-akhigbe/vet_clinic/assets/12002619/6c3d4335-429a-49a3-affc-dee2e50732a2">

- Details for the most recent visit: animal information, vet information, and date of visit.
<img width="766" alt="Screenshot 2023-06-10 at 6 13 26 PM" src="https://github.com/peter-akhigbe/vet_clinic/assets/12002619/8834cef9-c808-4952-a37d-995bd22e6239">

- How many visits were with a vet that did not specialize in that animal's species?
<img width="808" alt="Screenshot 2023-06-10 at 6 14 40 PM" src="https://github.com/peter-akhigbe/vet_clinic/assets/12002619/d738caf4-5a5e-40c8-810c-735a124b741d">

- What specialty should Maisy Smith consider getting? Look for the species she gets the most.
<img width="878" alt="Screenshot 2023-06-10 at 6 15 19 PM" src="https://github.com/peter-akhigbe/vet_clinic/assets/12002619/bb11a0b6-8144-4763-932f-81e91a637657">

2023-06-10 17:47 UTC, Zuhaib042 requested changes
Hi @peter-akhigbe 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://media.giphy.com/media/4xsT7Fa4IxbMCNroH3/giphy.gif)

## Highlights
✅ Writing good queries
✅ Descriptive PR
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-10 17:47 UTC, Zuhaib042 commented on queries.sql
> +  AND vt.name = 'Maisy Smith';
-  [ ] Here you are only displaying Maisy Smith name. the requirement is to display the animal name. kindly consider fixing this query. you can show animal name by writing JOINs like this:
```
JOIN visits ON visits.animals_id = animals.id
JOIN vets ON vets.id = visits.vets_id
```
Obviously you have to select the animals.name in the first line as well.

2023-06-10 17:47 UTC, Zuhaib042 commented on queries.sql
> +
-  [ ] Kindly fixing this query. right now in the result you have `0`. but in reality the result of this query should be `Digimon, 6` because Maisy smith have paid 6 visits to this species.

2023-06-10 20:16 UTC, peter-akhigbe commented
## Updated Queries

- Who was Maisy Smith's first visit?
<img width="823" alt="Screenshot 2023-06-10 at 9 11 37 PM" src="https://github.com/peter-akhigbe/vet_clinic/assets/12002619/45add90e-1aa9-49db-b6f4-9ad4781cd443">

<img width="570" alt="Screenshot 2023-06-10 at 9 12 45 PM" src="https://github.com/peter-akhigbe/vet_clinic/assets/12002619/a45577d2-33a2-42fe-aabf-51a9c400bc50">

- What specialty should Maisy Smith consider getting? Look for the species she gets the most.
<img width="823" alt="Screenshot 2023-06-10 at 9 11 37 PM" src="https://github.com/peter-akhigbe/vet_clinic/assets/12002619/3b54481c-7cc7-4155-9183-0442a0b8a36b">

<img width="570" alt="Screenshot 2023-06-10 at 9 13 06 PM" src="https://github.com/peter-akhigbe/vet_clinic/assets/12002619/3bd29397-cd42-442f-bbd5-0ddeead45359">

2023-06-10 20:22 UTC, tugsem commented
## STATUS: APPROVED 👍🎯  
Hello @peter-akhigbe 👋 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights ⭐ 
✔️ queries are corrected as required
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-10 08:55 UTC, merged

2023-07-15 10:37 UTC, CollinsTatang reviewed
# Approved 👏  
### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._